# Generated by Django 3.2.16 on 2025-01-30 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250130_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать только буквы, цифры и следующие символы @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
