# Generated by Django 3.2.16 on 2025-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20250203_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recipes_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='recipes.FavoriteRecipe', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
    ]
